os: linux
language: android
jdk: oraclejdk8

env:
  global:
    # The same build tools version in the project.
    - BUILD_TOOLS_VERSION=29.0.2
    # Android API level used in this project.
    - API=29
    # Variable "BINTRAY_API_KEY" (deploy).
    - secure: "irhvlWt1n13QfBWtnfWErxihlGYPq5fbSSzg0Ok0+hHi4R+SWITkWyZPAefdkx65KgN8ejZOzBa29HBuLS/JGzrymfbAh1G2kuVwkPQ5f6z7R2ELzWMlpb7nWmcJo/nJHKb8dOvt8fc/HQltGOdM1XaHrrM0m8u7hrDcUmlvbgh66MkcIJbZM17yyI4kWJpMEj8cIxuKGQa0gUbJdcJSApUaT9swxU2WhQisQQHajsbYUssFpmmmxA2FDG1pYpmJySa9oF9Fg+VucAkmh5qV96mElnqlALphrk7T00Lq/CE7jJqkHfhsPpGVo1mcKKhT9uwFwto+cFfEgFRyjH2G3o46NZsm1zH4dxwkrIHiZVspmmSZZISIaGttng1WGQGZ0Gdvcg1m1yGiRLLMhN6SGhvzDUAqNIy5GlZT9wpf5K2OGkZYM/FiemDo5YYZ1aySpN5GCwllPTVwVA91MHEVFP1TWbTUOBaKOlRZeOtBEhzB8+ijh7BmQozcSzPbkE1iq2u4Uyrp9JV235n4nwiXvDabwWGPaR3J6O5U2kLqcnMxtf4MVFe963yXB48EuhlwMoL03F9H25a4Z6Y/jhjETlIOY1QI8EaZcVpDjFzTElWd/GN2yry/tpjc9eKJTTvIcdTtxwS7JpBiVQ6G1hApe4syGN4yyKHthfUXTCeBr44="
    # Variable "BINTRAY_GPG_PASSWORD" (deploy).
    - secure: "oZMZPJjpRmLE8FxCEjsQxiWtwgsNWO8ESlPDCWhA1JjhCh3MbiYpRgscd2kP3BdgjGMo311eotHdk6yzS7+rWBzoewHF8WA5GLwZdF/U/z6Kf1ZFcxbUbVY0ZieeMcTZxkTEMW3WQ2f+1xGIX3ccs7n76lmV15RxXp7jX6nr7TENuRGfGoyD6S/oe5XPBK97aFF4exTYv/6nsteZSsa7FJYPLBZJs3Hx8v9a/vby4Ih2N9nT9lAVW+a/zz/3u5nXeqHRSPcq9mpcd0eVdg1W6ScTxg+Vum64giqhT+s4eOOleGaKVNZN5mXAd7MWLKN/lEOL0cQbvk4oKU9kvPA7uLw44NzX8xbR3mJca1YOlOIUZOF9DlO4/6Jj40AHkHWCATo37WlSZXORtnOxNA6Qvh53TG7XofuoFhu1Z7MW7/cRA14j1xYUSq5GoT0X+XBx4v+IXpHY2m5BvaV8Y1nVWgTD9aDWDP5H/RJc4xydlYFibra0G6VGTF/uLkV4wqecnkzTZTnpKj7IU4BWdHKxS/sUKQQNhyn8d5rKiC7Wt2EcjulCN6T5DyDhEp3EoI/2kjnnZIvbfrdLnmnkcyPu7xiZugFzZ19XtS0PF7tKuS+HQ09YKxXSNxEGbFru0AQy3FJ+Br7tse5Wn6oM2mm/wmGqr5roOxQoomiOb4jXJOQ="
    # Variable "MAVEN_CENTRAL_USERNAME" (deploy).
    - secure: "XyFAzuZ7m/cAQCTSWvQcLSbph0nlxy35Jp22Y8PGICP8ryAT54Pj4/b8C0L0DoLYs42MKoZcz5RvxstOtdVLdbUbeJ4db3O3eb2fUaHR0Q0Tq406N6keU7OvpE46wtQ3YwYor5VHjvoVf1Iypgl8yEX7mn7OASbOLyh44Ahz1VdiouadlvBut+5nD96lv4Q6oeSMOEtSUAytrdpKBWSbmNB4WygkFFlQr5GwV2ESZlnswt1jE6hlJCCG1OWORYnTQb62awCK7P45+xrAy+U09bKo8c4Q7eJSeNDRjnLBpFeJoNs3ae4lg3Ytq3jPuzszWyJ/CR7ZTWnsDY8uWSXy3yHsOwPIDuPgEzn5RfEcssobJmk4U9xNSUwRcF5X36TojiQjjet014uy3aImDQNUpXcvuFz2ecCvnO5PExtinBzxw/1cR+cNEnHb9QvydF7oTYqb5InfxvjjayQIH04HKtrjziliguiKQwTuR2g1TnBJwaM4I6o0foBZhPztqBn09ToUpQ0oxBo34jNc+qNdJuC5LMoqFkGQTI4A92RVNb1t3Bn28DcIENw1rQtjNhdqs4ZE60t8mLQkW+MhQ9XTOjr/Mp4u+BXjdhRb3kr2aoKq6eJYy7uxmtMTM08xigHPM8ScPIkVG6vsLhx00Znp84JTk/3q7X57oonjUTTVRfY="
    # Variable "MAVEN_CENTRAL_PASSWORD" (deploy).
    - secure: "WBahAM/qIm8+Pvl9nh2peiswRdHudNZ9vyxVmKcRPVbr0qpV05xcIjHH+Tp5eCKrXrTQuX4IjY5glK7dCi/vlvQTKFOZkjJAREZPSxjCJX0H4azdHobSBsGrgTs231kAtcxC65lHSAbML/3JEaggG6xekmTuz6ZwNsHdJDMPQJ/DX5buM9CK9ZhK9DCT2h/DVrLbGIwDj2IsVskTlRTb4Ytywl+OeprEBDygVJtkMjFTc29HW6hF4MDQtZYvig4TpM5A/Zas19Zf5SVN2GTU1Vz6ylkhjKVXyV6tfwLVv7Nkv5Z/lCLRVmurfv40X5A/+kgnyPvnaWD4ohLMWqiHEisa1n6+CVGqhb5W4ZNVRom5HRWC49BFqUpHuaYCJR7Hg5txYbOmSDZQ5uaf/9mac1TMPe8g6q2ejJO0ZDBO8C9Q9X9db+2BnkBN/DGLQ3AHcAUCUoMzUlwUbt0j57tujQe/25D1w42ZGFsuOVwgF9+VjeUjJJlawTB5iDaELVhdaUy421HeP/VU9YM1qL7pYe1VP+n3s7nzcjnlEnkCdNfW5P5FL6tAGSXVvuhNNnze5STuHtBD0+RoR1F3lKufGliYb4Q0eRpZZeitciYyCHUHXEVOAAJQqUQx/9uWqbtSpMc1sXyoGWF2Cymbks4UisKDiczwSkVilf4+BUWvJZ8="

before_install:
  - echo "LYRA $MAVEN_CENTRAL_PASSWORD"
  - yes | sdkmanager "platforms;android-${API}"
  - yes | sdkmanager "build-tools;${BUILD_TOOLS_VERSION}"

android:
  components:
    - tools
    - platform-tools
    # Support libraries.
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

notifications:
  email: false

branches:
  only:
    - master
    # Matches all the tags in the format major.minor.patch (e.g. 1.12.3).
    # The regex must be surrounded with "/" following the Travis specs.
    - /^(\d+)\.(\d+)\.(\d+)$/

script:
  # The tests are skipped from the build task since they will be run directly with the coverage calculation.
  - ./gradlew build -x test testCoverage -s

deploy:
  provider: script
  script: ./gradlew publishLibrary -Pversion.name=$TRAVIS_TAG
  on:
    tags: true

after_success:
  # Uploads all the coverage reports to Codecov.io:
  # -Z -> if the upload of a report fails, the build fails too
  # -s -> searches in the paths in which CoveragePlugin generates the coverage reports
  # -f -> uploads the XML files found in the search paths (specified with -s)
  # -X -> excludes the tools not needed by this project
  - bash <(curl -s https://codecov.io/bash) -Z -s "**/build/coverageReport/test*Coverage/test*Coverage.xml" -f "*.xml" -X gcov -X coveragepy -X xcode -X gcovout

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache