os: linux
language: android
jdk: oraclejdk8

env:
  global:
    # The same build tools version in the project.
    - BUILD_TOOLS_VERSION=29.0.2
    # Android API level used in this project.
    - API=29
    # Deploy property named "bintray.api.key".
    - secure: "eLnrys3zgaXX9C9v+CfWPXGkotwEMeT1AZtQmBwJSXAQ13yjrhAiHUkqWDzIuGO4HLBFouexnzj4/q+4O7QuJzUzrAblJnVa+qd/0sQ0Ed2g/zu1XX2TWi2wd/Gfa3qa4nDsrvm29RD3CEgPy12finwkyOP4bTKyxv2H1oM5Sd1BNw8chB5uFwx5H512BBPW2E9wl++B/WxOXtjr0tDP/VFi1aM9+sMBddlrLcxp5CQWkF38eomcDrsClY/5Iw7rikvjBng2myDpjmN57KrDzjuh20zv4rin6iUnSbVFMVVStdJB2lrlJ43WvJZeVyZpUTVF2HQaYjca1aD5W9LIO2/XP4sc4jGxlFB1YPbV77x1Xl/EvGkv368y73pIiW9xWGQMt3EfD9jJ469+cpOKGFySeSeiRCCBoIV5oLOSDfG51+8brxu5St+gMdcVl8nfcg+hQqOuNIMRdBvW92NlBNN3BEJ9ET7xQR6n7VV+lSM4ReDLnhIinUOO7zuwv48TjTl2+ddrSturjDjhhATl3R2wJaO85AeAUvAooxazPe6NLftBu7TOsi/nWgfLwnsFcn4Dmyu4KMJXPqqDWqBjODbpGahHUjo7v6Nt471uxIDaDoqwgioEPsafQ/WsPCmgSoMA2sqjb8bgYKW4+J8811jVGBONu2ipzPSC+z1a51w="
    # Deploy property named "bintray.gpg.password".
#    - secure: "lTYm/2zBal/ZyaKbTDjW7PH9E15vC0lUD/fFHTytpSq5WOMzW91OisA4GTmFrP9H4lpC7HAznYJcdaVgcVZiKVNu6BS7gzKziRZ1v+NP65MDWV7aOXw/J6iKsHEmo4DD3tmJhSgSXgO0sBaVyu5oJVHszrf833v0Z9VybLVW/XUpCXxHpRxC/3APTALRzX8t1IK4kBf4jME/Jfa/xIuS0yFB32Wpg3NQOmwqjoOq5AyGt2PuCWvtwuVepENvgf82abDtOEJkOafB2haOq86W8aXehjDC6T8fNzFghVFy4flcvIWiCAUkg6Pbktpnogrb+BcAqbvSE8GAUAs17FbFbnJkL8ihzBVTu+QeQTEnqpmUJcV88Oex1eM047fyISHJUO++WmyQHeICHsgz2I6xOzlX73rzkI2gLAYbvItHtNGQvLGEVTYrlVQrfb4XSc5n0knrsPmsiKszk0gA2iQGENf5jf2oOSqUgFT6oJXaA5U9sLjjbvheBZQioOqGja8NA4d4rynG0X0Twlhj3RZcqC8GCb7jhcNW7RCanb8O4mIF2NsreCieClmnM0YxmGejwUzjqIWe+2S2xlUQs3qlcxaTP08U9akZn8+FWkgqmpr0vEY+uufK1VVm6Hsk2oua7yx6lFcVheJbK2r2TOIWnUZFcljSLonfMx8PAsgfjwY="
    # Deploy property named "maven.central.username".
#    - secure: "EUp8E7h0je+t0FwORKp3Wy13fp/pH03NB9GsAHf828W2gPDbVohomHAOKE6HQNCK3sizFgQKY+nFStK4lv1dWvuxKOyt2Lo597Eb9ZTc15LPdrYoN/5exzfRVGT5/8isl43zZcci/vf4gxXgAPVhJn0TXjFdlE564FkZfNrV722a7+xj9a4ojfAWQqGaPLIKKJNA3lvUEM+mKZBetrQbjhRSX9T4Q6pIn7JKlTAbbbeUPiI2Pg8zOzvQpWhpNoDXISZZRaSCcoiiK0soJmfkba2ZsYyM54ixZUYodC1FjE2U/Via+86eOKN0NCKXWrbADCydWcm3VKTtr40ggl0UKuWyzgOtkJVosaeiy6bBPlsB83JYJX70up2/+CYQnwT7V9nmZSogecKUcCesD/oNkNK9XULUxKaNzW01+A8/R/qSlHTvqzJUXTRfsHJMdAdGaURkx3Sp5/3GmmdR/GIUQr7Lx6VHacw3V6iyDoXAH7qRG9ZOq330mJbpKFGEm35UK6otIx0CvlkCOJv6cmbwEaLic9X3Gq4qzeZg+HygVtu58Z1wc7G6SaA8zi0StqUWSrkVRWLT17z5AwRH8aNVleuSEZi2fK7ZmbKGVo5GJ8AfBMtQxPMD1FCaZwX4vYIBYZ90uoGM/cPtTrYY35NZcfl7glRMxI1G+cU+VsCP1X0="
    # Deploy property named "maven.central.password".
#    - secure: "FeI1/YC5dThV+JCAR0TVJlUT1oZsqrv3+7WauBal8cAxTnvjVels0DglWAutriGM8X5tqR7qk86mRj2PTiaMcBRSJcZycEqHadcng19Muuo9LcIsj6+yAKARRbxS8aNNytkSdtu5i445W5CS1YGw0xlxpKKLexRQkqMShSFj6i1OFegOvjJgI5Fhbj+xrLAV237iB9c9N/6QAoKu7/gV6CLuRb9uZgNcqiXmBrUAT8Q/PwHFAzgI2KtFik2hRHrWORS50qtr4N7bFHB4TQQ3eD1nP1+lKlbr2JxOACzFKZ5ExydR1e1I8hEy5BrGTRRAhSwtUxyba/MOirCqkZl/0zp87y6lOD8hyLe0f1wnJWib2mwHfUgjoaVEWoueiEVnylBDWGWXFFWe/mku4TRO9E/gJdbKYFc2lxeAi3cIX/gqo+v9EUc1VsAToQ09oLbXt7Bp/RZYwhgoLqGJ9oVnHzOAQM1GTVkmfNCwBS2Pht6kQ2aaJ527LnX7svTILUovlHrOVn63yMiivGdwGAW8xZeEbq/sgO+850ZGmAIOKXmmnRYXJQXYMIVQDiy7r9NQh9ME36wn3mGPmY6en/Q6YjQsUf6jDNhn6JsvhDQDzMH9eU7sBhLXEQsssV13edWUoVJlPP1O3BmKLQpV1QQdaPvO7wb8GooYHFv41cZgZaM="

before_install:
  - yes | sdkmanager "platforms;android-${API}"
  - yes | sdkmanager "build-tools;${BUILD_TOOLS_VERSION}"

android:
  components:
    - tools
    - platform-tools
    # Support libraries.
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

notifications:
  email: false

branches:
  only:
    - master
    # Matches all the tags in the format major.minor.patch (e.g. 1.12.3).
    # The regex must be surrounded with "/" following the Travis specs.
    - /^(\d+)\.(\d+)\.(\d+)$/

script:
  # The tests are skipped from the build task since they will be run directly with the coverage calculation.
  - ./gradlew build -x test testCoverage -s

deploy:
  provider: script
  script: ./gradlew publishLibrary -Pversion.name=$TRAVIS_TAG
  on:
    tags: true

after_success:
  # Uploads all the coverage reports to Codecov.io:
  # -Z -> if the upload of a report fails, the build fails too
  # -s -> searches in the paths in which CoveragePlugin generates the coverage reports
  # -f -> uploads the XML files found in the search paths (specified with -s)
  # -X -> excludes the tools not needed by this project
  - bash <(curl -s https://codecov.io/bash) -Z -s "**/build/coverageReport/test*Coverage/test*Coverage.xml" -f "*.xml" -X gcov -X coveragepy -X xcode -X gcovout

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache