name: GitHub CI Deploy

on:
  push:
    tags:
      # Matches all the tags in the format major.minor.patch (e.g. 1.12.3).
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  CI: true
  MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build -s
      - name: Extract tag
        id: tag-extractor
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/*/}
      - name: Deploy
        env:
          DEPLOY_TAG: ${{ steps.tag-extractor.outputs.TAG }}
        run: ./gradlew publishLibrary --no-parallel -s \
          -PVERSION_NAME=$DEPLOY_TAG \
          -PmavenCentralRepositoryUsername=$MAVEN_CENTRAL_USERNAME \
          -PmavenCentralRepositoryPassword=$MAVEN_CENTRAL_PASSWORD
